### Homework 3 Numpy Arrays

1. Open `cars.csv` in jupyter and look at the data. (Double click `cars.csv` to open in a new tab).
2. We are converting each **column** into an numpy array.
3. Notice we have text, integer and float data. 
4. Take care not to overwrite your starter code.

In [ ]:
#Starter code. Do NOT modify this cell
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('cars.csv',delimiter=';')


# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()


# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin']  
                   

In [34]:
df

Car   MPG  Cylinders  Displacement  Horsepower  \
0    Chevrolet Chevelle Malibu  18.0          8         307.0       130.0   
1            Buick Skylark 320  15.0          8         350.0       165.0   
2           Plymouth Satellite  18.0          8         318.0       150.0   
3                AMC Rebel SST  16.0          8         304.0       150.0   
4                  Ford Torino  17.0          8         302.0       140.0   
..                         ...   ...        ...           ...         ...   
401            Ford Mustang GL  27.0          4         140.0        86.0   
402          Volkswagen Pickup  44.0          4          97.0        52.0   
403              Dodge Rampage  32.0          4         135.0        84.0   
404                Ford Ranger  28.0          4         120.0        79.0   
405                 Chevy S-10  31.0          4         119.0        82.0   

     Weight  Acceleration  Model  Origin  
0    3504.0          12.0     70      US  
1    3693.0          11.5     70      US  
2    3436.0          11.0     70      US  
3    3433.0          12.0     70      US  
4    3449.0          10.5     70      US  
..      ...           ...    ...     ...  
401  2790.0          15.6     82      US  
402  2130.0          24.6     82  Europe  
403  2295.0          11.6     82      US  
404  2625.0          18.6     82      US  
405  2720.0          19.4     82      US  

[406 rows x 9 columns]

In [12]:
import pandas as pd
import numpy as np 
df = pd.read_csv('cars.csv',delimiter=';')
print(df)


                           Car   MPG  Cylinders  Displacement  Horsepower  \
0    Chevrolet Chevelle Malibu  18.0          8         307.0       130.0   
1            Buick Skylark 320  15.0          8         350.0       165.0   
2           Plymouth Satellite  18.0          8         318.0       150.0   
3                AMC Rebel SST  16.0          8         304.0       150.0   
4                  Ford Torino  17.0          8         302.0       140.0   
..                         ...   ...        ...           ...         ...   
401            Ford Mustang GL  27.0          4         140.0        86.0   
402          Volkswagen Pickup  44.0          4          97.0        52.0   
403              Dodge Rampage  32.0          4         135.0        84.0   
404                Ford Ranger  28.0          4         120.0        79.0   
405                 Chevy S-10  31.0          4         119.0        82.0   

     Weight  Acceleration  Model  Origin  
0    3504.0          12.0     70

In [13]:
print(df['Car'])

0      Chevrolet Chevelle Malibu
1              Buick Skylark 320
2             Plymouth Satellite
3                  AMC Rebel SST
4                    Ford Torino
                 ...            
401              Ford Mustang GL
402            Volkswagen Pickup
403                Dodge Rampage
404                  Ford Ranger
405                   Chevy S-10
Name: Car, Length: 406, dtype: object


In [1]:
import numpy as np

headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])
print(headers)

['Car' 'MPG' 'Cylinders' 'Displacement' 'Horsepower' 'Weight'
 'Acceleration' 'Model' 'Origin']


1. How can you get help on `np.array`?  

Call `dir()` on `npi.array`. 

Call `dir()` on `car`.

Note the difference. `car` has methods and attributes we can use.

In [19]:
dir(np.array)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__text_signature__']

In [21]:
dir('car')

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',


2. What are the numpy datatypes for the `car`,`mpg`, `horsepower` and `origin` arrays? (Hint: Not `type(car)` and use `print()` to print the numpy type.)

In [92]:
df = pd.read_csv('cars.csv',delimiter=';')
df
df.columns
print(df['Car'])
print(df['MPG'])
print(df['Horsepower'])
print(df['Origin'])

0      Chevrolet Chevelle Malibu
1              Buick Skylark 320
2             Plymouth Satellite
3                  AMC Rebel SST
4                    Ford Torino
                 ...            
401              Ford Mustang GL
402            Volkswagen Pickup
403                Dodge Rampage
404                  Ford Ranger
405                   Chevy S-10
Name: Car, Length: 406, dtype: object
0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ... 
401    27.0
402    44.0
403    32.0
404    28.0
405    31.0
Name: MPG, Length: 406, dtype: float64
0      130.0
1      165.0
2      150.0
3      150.0
4      140.0
       ...  
401     86.0
402     52.0
403     84.0
404     79.0
405     82.0
Name: Horsepower, Length: 406, dtype: float64
0          US
1          US
2          US
3          US
4          US
        ...  
401        US
402    Europe
403        US
404        US
405        US
Name: Origin, Length: 406, dtype: object


3. `numpy` is often imported as `np`. What is this action called? Why might you do this? 

In [ ]:
creating an alias; for faster coding

4. Each of the arrays (cars, mpg, cylinders, etc..) has how many dimensions? Show how to find this using code. 

In [2]:
import numpy as np
import pandas as pd
df = pd.read_csv('cars.csv',delimiter=';')
print(df.ndim)

2


5. Show how to:

- multiply the `mpg` array by 12.
- divide the `mpg` array by 3.
- raise the `mpg` array to the power of 4.
- take the square root of the `mpg` array.

In [14]:
np.true_divide(mpg, x)

array([1.5       , 1.25      , 1.5       , 1.33333333, 1.41666667,
       1.25      , 1.16666667, 1.16666667, 1.16666667, 1.25      ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       1.25      , 1.16666667, 0.        , 1.25      , 1.16666667,
       2.        , 1.83333333, 1.5       , 1.75      , 2.25      ,
       2.16666667, 2.08333333, 2.        , 2.08333333, 2.16666667,
       1.75      , 0.83333333, 0.83333333, 0.91666667, 0.75      ,
       2.25      , 2.33333333, 2.08333333, 2.08333333, 0.        ,
       1.58333333, 1.33333333, 1.41666667, 1.58333333, 1.5       ,
       1.16666667, 1.16666667, 1.16666667, 1.16666667, 1.        ,
       1.08333333, 1.08333333, 1.5       , 1.83333333, 1.58333333,
       1.5       , 1.91666667, 2.33333333, 2.5       , 2.5       ,
       2.58333333, 2.91666667, 2.25      , 2.16666667, 2.        ,
       2.08333333, 1.91666667, 1.66666667, 1.75      , 1.08333333,
       1.16666667, 1.25      , 1.16666667, 1.41666667, 0.91666

In [115]:
np.sqrt(x)

array([[[1.        , 1.41421356, 1.73205081]],

       [[2.        , 2.23606798, 2.44948974]],

       [[2.64575131, 2.82842712, 3.        ]],

       [[1.        , 1.41421356, 1.73205081]]])

In [2]:
df = pd.read_csv('cars.csv',delimiter=';')
mpg = df.MPG.to_numpy()
np.power(x)
x = 12 **4

NameError: name 'pd' is not defined

6. What is the ___ of `horsepower`?
- sum
- min
- max
- median
- Optional: mode (May need to google help)

In [6]:
import pandas as pd
import numpy as np
df = pd.read_csv('cars.csv',delimiter=';')
print(df)

print('sum:' + str(np.sum(horsepower)))
print('min' + str(np.min(horsepower)))
print('min' + str(np.max(horsepower)))
print('min' + str(np.median(horsepower)))

                           Car   MPG  Cylinders  Displacement  Horsepower  \
0    Chevrolet Chevelle Malibu  18.0          8         307.0       130.0   
1            Buick Skylark 320  15.0          8         350.0       165.0   
2           Plymouth Satellite  18.0          8         318.0       150.0   
3                AMC Rebel SST  16.0          8         304.0       150.0   
4                  Ford Torino  17.0          8         302.0       140.0   
..                         ...   ...        ...           ...         ...   
401            Ford Mustang GL  27.0          4         140.0        86.0   
402          Volkswagen Pickup  44.0          4          97.0        52.0   
403              Dodge Rampage  32.0          4         135.0        84.0   
404                Ford Ranger  28.0          4         120.0        79.0   
405                 Chevy S-10  31.0          4         119.0        82.0   

     Weight  Acceleration  Model  Origin  
0    3504.0          12.0     70

NameError: name 'horsepower' is not defined

In [7]:
np.sum[0,9]

TypeError: 'function' object is not subscriptable

7. Select a subset of `acceleration`. 

- Select only the first 5 elements.
- Select every other element (new selection).

In [100]:
import numpy as np
import pandas as pd
df = pd.read_csv('cars.csv',delimiter=';')
print(df.columns)
print(df['Acceleration'][0:5])
print(df['MPG'][0:5])

Index(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight',
       'Acceleration', 'Model', 'Origin'],
      dtype='object')
0    12.0
1    11.5
2    11.0
3    12.0
4    10.5
Name: Acceleration, dtype: float64
0    18.0
1    15.0
2    18.0
3    16.0
4    17.0
Name: MPG, dtype: float64


8. Show how to select the number `99` in the array below. 

In [79]:
select_99 = np.array([[1,2,3],                #[row,colum]
                      [4,5,99]])               # start at 0
select_99[1,2]

99

9. Select the last element in each subarray (do this with one operation.)

In [80]:
select_more = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
# returns array([3, 6, 9])
select_more[:,2]

array([3, 6, 9])

10. Use the built-in `np.lookfor()` function to search for `'log'`.

Use the function you find and apply it to `mpg`.

In [20]:
np.lookfor(['mpg'])

Search results for '['mpg']'
----------------------------
Nothing found.


11. You your google skills to find the unique items in `origin`. (This may not have been covered in the readings.)

In [58]:
import numpy as np
x= np.array([(1,2,3),(4,5,6)])
print(x)
print(x.shape)
print(x.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [71]:
x= np.array([[(1,2,3)],[(4,5,6)],[(7,8,9)]])
print(x)
print(x.shape)
print(x.ndim)

[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]
(3, 1, 3)
3


In [ ]:
x= np.array([[(1,2,)],[(4,5,)]],[[(7,8,)],[(9,10)]],[[(11,12,)],[(14,15,)]],[[(17,18,)],[(20,21,)]])
print(x)

#come back (4D array)


13.Use boolean indexing to create an array of `True/False` using `origin` and the value 'US'.

In [18]:
import numpy as np
import pandas as pd
df = pd.read_csv('cars.csv',delimiter=';')
print(df.columns)
print(df['origin'][0:9])


Index(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight',
       'Acceleration', 'Model', 'Origin'],
      dtype='object')


KeyError: 'origin'

14. Apply your index (from above) to the `car` array. You should now only see cars that are of US origin. 

In [5]:
import numpy as np
import pandas as pd
df = pd.read_csv('cars.csv',delimiter=';')
print(df.columns)
print(df['car'][0:9])

Index(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight',
       'Acceleration', 'Model', 'Origin'],
      dtype='object')


KeyError: 'car'

**The remaining questions are OPTIONAL**: The readings did not address all of these so you may have to use some "Google-Fu". 

1.What is an identity matrix? 
Create an identiy matrix of size 5 using an np method. 

2. Transpose the following array. 

In [ ]:
transpose_me = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])


3. Why does this multiplication operation fail? 

In [ ]:
arr1 = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
arr2 = np.array([[1,2,3],
                      [4,5,6]])

arr1 * arr2

Use numpy to answer the following questions. 

4. What is the average horsepower for `Europe` cars? (Hint: create boolean index of 'US' apply it to horsepower and perform the calculation.)

5. On average are Japanse cars more fuel efficient than US cars? 

6. What is the correlation coefficient of `mpg` and `weight`?

7. Why might you prefer an `np.array()` over a Python `list`? And when is a Python `list` preferred? 